- name: installing jenkins in ubuntu 16.04
  hosts: all
  gather_facts: False
  become: True

  tasks:
#    - name: Update apt-get repo and cache
#      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: install python 2
      apt: 
        pkg: ['python-minimal']
        state: present

    - name: install curl and git
      apt: 
        pkg: ['vim','git','curl']
        state: present

    - name: adding jenkins gpg key
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins-ci.org.key
        state: present

    - name: jeknins repository to system
      apt_repository:
        repo: http://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: installing jenkins
      apt:
        name: jenkins
        state: present
        update_cache: yes

    - name: adding jenkins to startup
      service:
        name: jenkins
        state: started
        enabled: yes

    - name: printing jenkins default administration password
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: jenkins_default_admin_password
    
    - debug:
        msg: "{{ jenkins_default_admin_password.stdout }}"
